version: "3"

services: 
  app:
    container_name: food-expire
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - my-app

  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - my-app
    depends_on:
      - mongo

  mongo:
    container_name: FE-Mongo
    image: mongo
    ports:
      - "27017:27017"

networks:
  my-app:
    driver: bridge

volumes: 
  mongo-data:
    driver: local